### ISSUE TITLE
it seems that modules.name in options does not work as described in r.js optimizer 

### ISSUE THREAD

**Issue by riotkkwok** [jlouns/gulp-requirejs-optimize#3] opened 2015-07-03 09:09 UTC
Here is my directory of workspace.
![12](https://cloud.githubusercontent.com/assets/10059303/8496069/f1a0fda4-21a4-11e5-9ccc-048cefa3b8dd.PNG)

And I wrote the code in gulpfile.js as below.
![11](https://cloud.githubusercontent.com/assets/10059303/8496162/976c3956-21a5-11e5-9153-4842de39485d.PNG)

I want only topics.js to be handled by this plugin. However, the plugin does not run, even I tried the values as below:
'topics.js'
'src/js/topics'
'src/js/topics.js'
'./src/js/topics'
'./src/js/topics.js'

As I understood(don't know it is correct or not), the modules which are defined in option.module should be handled by the plugin.

**Comment by jlouns** [comment] 2015-07-06 14:45
It looks like this is definitely an issue. The `modules` option will not work with this plugin. I'm going to add a note to the readme.

Luckily, there's a good alternative. I'd write the task like this:

``` js
gulp.src('src/js/topics.js')
  .pipe(requirejsOptimize({
    optimize: 'none',
    mainConfigFile: 'src/js/rConfig.js'
  })
  .pipe(gulp.dest('mobile/js/'))
  .pipe(notify({ message: 'JS requirejs task complete' }));
```

As you add more modules, you can just add more files to the `gulp.src` call. The problem with the modules option for `r.js` is that it looks like it doesn't pass the text of each module to the `options.out` function, which means we can't stream the optimized file contents, and it won't work with the plugin. The way I wrote it above, any file that is streamed to the plugin by `gulp.src` should be optimized as a module and passed to your `gulp.dest` directory.

**Comment by pavel06081991** [comment] 2015-07-22 07:21
I also have the same issue. And I tried to use your solution

``` javascript
gulp.src('src/js/topics.js')
  .pipe(requirejsOptimize({
    optimize: 'none',
    mainConfigFile: 'src/js/rConfig.js'
  })
  .pipe(gulp.dest('mobile/js/'))
```

 but it does not work without "name" property. I mean I have to do like this for your plugin to work:

``` javascript
gulp.src('src/js/topics.js')
  .pipe(requirejsOptimize({
    optimize: 'none',
    mainConfigFile: 'src/js/rConfig.js',
    name: 'src/js/topics'
  })
  .pipe(gulp.dest('mobile/js/'))
```

And if we have array of modules passed to gulp.src, then how to add array of names?..

**Comment by riotkkwok** [comment] 2015-07-30 10:30
Finally, I use gulp-filter to filter all the js files I need as an interim solution.

```
var rjsFilter = filter(['edit.js', 'ranking.js', 'topics.js']);
gulp.src('src/js/**/*.js')
  .pipe(rjsFilter)
  .pipe(requirejsOptimize({
    optimize: 'none',
    mainConfigFile: 'src/js/rConfig.js'
  })
  .pipe(rjsFilter.restore())
  .pipe(gulp.dest('mobile/js/'))
```

**Comment by jlouns** [comment] 2015-08-06 03:00
@riotkkwok your solution is what I would recommend if you want to optimize those three files and copy the rest to the destination directory. If you just want to optimize the three files and not copy the rest then I'd do something like this:

``` js
gulp.src(['src/js/edit.js', 'src/js/ranking.js', 'src/js/topics.js'])
  .pipe(requirejsOptimize({
    optimize: 'none',
    mainConfigFile: 'src/js/rConfig.js'
  })
  .pipe(gulp.dest('mobile/js/'));
```

**Comment by jlouns** [comment] 2015-08-06 03:02
@pavel06081991 I'm not able to reproduce your issue. I made a very small test project [here](https://github.com/jlouns/gulp-requirejs-optimize-test) that demonstrates how to optimize an array of files.

If you're still having your issue and can make a simple project with your issue I can take a look.

**Comment by pmhou** [comment] 2015-08-10 11:40
How would you specify module(s) to exclude? This is normally defined in the modules key 

``` javascript
modules: [
    {
        name: 'app/home',
        exclude: ['main']
    }
]



```

**Comment by jlouns** [comment] 2015-08-10 14:30
@pmhou Just specify it in the root of the config. See [here](https://github.com/jrburke/r.js/blob/master/build/example.build.js#L434).

``` js
gulp.task('scripts', function () {
    return gulp.src('src/app/home.js')
        .pipe(requirejsOptimize({
            name: 'app/home',
            exclude: ['main']
        })
        .pipe(gulp.dest('dist'));
});
```

If you need different excludes for different modules, use an options generating function as input to the plugin and select the exclude based on the module passed in. For example:

``` js
var excludes = {
    'home': ['main'],
    'example_module_a': ['excluded_module_2'],
    'example_module_b': ['excluded_module_3']
};

gulp.task('scripts', function () {
    return gulp.src('src/app/*.js')
        .pipe(requirejsOptimize(function(file) {
            var filename = file.relative.split('.')[0];
            return {
                name: 'app/' + filename,
                exclude: excludes[filename]
            };
        }))
        .pipe(gulp.dest('dist'));
});
```

**Comment by jlouns** [comment] 2015-08-14 20:10
I'm going to close this. Feel free to reopen if any of you are still having issues.

**Closed as completed by jlouns** 2015-08-14 20:10 UTC
